package arigo

type Options struct {
	AllProxy                      string  `json:"all-proxy,omitempty"`
	AllProxyPassword              string  `json:"all-proxy-passwd,omitempty"`
	AllProxyUser                  string  `json:"all-proxy-user,omitempty"`
	AllowOverwrite                bool    `json:"allow-overwrite,omitempty,string"`
	AllowPieceLengthChange        bool    `json:"allow-piece-length-change,omitempty,string"`
	AlwaysResume                  bool    `json:"always-resume,omitempty,string"`
	AsyncDNS                      bool    `json:"async-dns,omitempty,string"`
	AutoFileRenaming              bool    `json:"auto-file-renaming,omitempty,string"`
	BtEnableHookAfterHashCheck    bool    `json:"bt-enable-hook-after-hash-check,omitempty,string"`
	BtEnableLpd                   bool    `json:"bt-enable-lpd,omitempty,string"`
	BtExcludeTracker              string  `json:"bt-exclude-tracker,omitempty"`
	BtExternalIP                  string  `json:"bt-external-ip,omitempty"`
	BtForceEncryption             bool    `json:"bt-force-encryption,omitempty,string"`
	BtHashCheckSeed               bool    `json:"bt-hash-check-seed,omitempty,string"`
	BtLoadSavedMetadata           bool    `json:"bt-load-saved-metadata,omitempty,string"`
	BtMaxPeers                    uint    `json:"bt-max-peers,omitempty,string"`
	BtMetadataOnly                bool    `json:"bt-metadata-only,omitempty,string"`
	BtMinCryptoLevel              string  `json:"bt-min-crypto-level,omitempty"`
	BtPrioritizePiece             string  `json:"bt-prioritize-piece,omitempty"`
	BtRemoveUnselectedFile        bool    `json:"bt-remove-unselected-file,omitempty,string"`
	BtRequestPeerSpeedLimit       string  `json:"bt-request-peer-speed-limit,omitempty"`
	BtRequireCrypto               bool    `json:"bt-require-crypto,omitempty,string"`
	BtSaveMetadata                bool    `json:"bt-save-metadata,omitempty,string"`
	BtSeedUnverified              bool    `json:"bt-seed-unverified,omitempty,string"`
	BtStopTimeout                 uint    `json:"bt-stop-timeout,omitempty,string"`
	BtTracker                     string  `json:"bt-tracker,omitempty"`
	BtTrackerConnectTimeout       uint    `json:"bt-tracker-connect-timeout,omitempty,string"`
	BtTrackerInterval             uint    `json:"bt-tracker-interval,omitempty,string"`
	BtTrackerTimeout              uint    `json:"bt-tracker-timeout,omitempty,string"`
	CheckIntegrity                bool    `json:"check-integrity,omitempty,string"`
	Checksum                      string  `json:"checksum,omitempty"`
	ConditionalGet                bool    `json:"conditional-get,omitempty,string"`
	ConnectTimeout                uint    `json:"connect-timeout,omitempty,string"`
	ContentDispositionDefaultUtf8 bool    `json:"content-disposition-default-utf8,omitempty,string"`
	Continue                      bool    `json:"continue,omitempty,string"`
	Dir                           string  `json:"dir,omitempty"`
	DryRun                        bool    `json:"dry-run,omitempty,string"`
	EnableHttpKeepAlive           bool    `json:"enable-http-keep-alive,omitempty,string"`
	EnableHttpPipelining          bool    `json:"enable-http-pipelining,omitempty,string"`
	EnableMmap                    bool    `json:"enable-mmap,omitempty,string"`
	EnablePeerExchange            bool    `json:"enable-peer-exchange,omitempty,string"`
	FileAllocation                string  `json:"file-allocation,omitempty"`
	FollowMetalink                bool    `json:"follow-metalink,omitempty,string"`
	FollowTorrent                 bool    `json:"follow-torrent,omitempty,string"`
	ForceSave                     bool    `json:"force-save,omitempty,string"`
	FtpPasswd                     string  `json:"ftp-passwd,omitempty"`
	FtpPasv                       bool    `json:"ftp-pasv,omitempty,string"`
	FtpProxy                      string  `json:"ftp-proxy,omitempty"`
	FtpProxyPasswd                string  `json:"ftp-proxy-passwd,omitempty"`
	FtpProxyUser                  string  `json:"ftp-proxy-user,omitempty"`
	FtpReuseConnection            bool    `json:"ftp-reuse-connection,omitempty,string"`
	FtpType                       string  `json:"ftp-type,omitempty"`
	FtpUser                       string  `json:"ftp-user,omitempty"`
	GID                           string  `json:"gid,omitempty"`
	HashCheckOnly                 bool    `json:"hash-check-only,omitempty,string"`
	Header                        string  `json:"header,omitempty"`
	HttpAcceptGzip                bool    `json:"http-accept-gzip,omitempty,string"`
	HttpAuthChallenge             bool    `json:"http-auth-challenge,omitempty,string"`
	HttpNoCache                   bool    `json:"http-no-cache,omitempty,string"`
	HttpPasswd                    string  `json:"http-passwd,omitempty"`
	HttpProxy                     string  `json:"http-proxy,omitempty"`
	HttpProxyPasswd               string  `json:"http-proxy-passwd,omitempty"`
	HttpProxyUser                 string  `json:"http-proxy-user,omitempty"`
	HttpUser                      string  `json:"http-user,omitempty"`
	HttpsProxy                    string  `json:"https-proxy,omitempty"`
	HttpsProxyPasswd              string  `json:"https-proxy-passwd,omitempty"`
	HttpsProxyUser                string  `json:"https-proxy-user,omitempty"`
	IndexOut                      uint    `json:"index-out,omitempty,string"`
	LowestSpeedLimit              uint    `json:"lowest-speed-limit,omitempty,string"`
	MaxConnectionPerServer        uint    `json:"max-connection-per-server,omitempty,string"`
	MaxDownloadLimit              uint    `json:"max-download-limit,omitempty,string"`
	MaxFileNotFound               uint    `json:"max-file-not-found,omitempty,string"`
	MaxMmapLimit                  uint    `json:"max-mmap-limit,omitempty,string"`
	MaxResumeFailureTries         uint    `json:"max-resume-failure-tries,omitempty,string"`
	MaxTries                      uint    `json:"max-tries,omitempty,string"`
	MaxUploadLimit                uint    `json:"max-upload-limit,omitempty,string"`
	MetalinkBaseUri               string  `json:"metalink-base-uri,omitempty"`
	MetalinkEnableUniqueProtocol  bool    `json:"metalink-enable-unique-protocol,omitempty,string"`
	MetalinkLanguage              string  `json:"metalink-language,omitempty"`
	MetalinkLocation              string  `json:"metalink-location,omitempty"`
	MetalinkOs                    string  `json:"metalink-os,omitempty"`
	MetalinkPreferredProtocol     string  `json:"metalink-preferred-protocol,omitempty"`
	MetalinkVersion               string  `json:"metalink-version,omitempty"`
	MinSplitSize                  uint    `json:"min-split-size,omitempty,string"`
	NoFileAllocationLimit         bool    `json:"no-file-allocation-limit,omitempty,string"`
	NoNetrc                       bool    `json:"no-netrc,omitempty,string"`
	NoProxy                       bool    `json:"no-proxy,omitempty,string"`
	Out                           string  `json:"out,omitempty"`
	ParameterizedUri              string  `json:"parameterized-uri,omitempty"`
	Pause                         bool    `json:"pause,omitempty,string"`
	PauseMetadata                 bool    `json:"pause-metadata,omitempty,string"`
	PieceLength                   string  `json:"piece-length,omitempty"`
	ProxyMethod                   string  `json:"proxy-method,omitempty"`
	RealtimeChunkChecksum         string  `json:"realtime-chunk-checksum,omitempty"`
	Referer                       string  `json:"referer,omitempty"`
	RemoteTime                    bool    `json:"remote-time,omitempty,string"`
	RemoveControlFile             string  `json:"remove-control-file,omitempty"`
	RetryWait                     uint    `json:"retry-wait,omitempty,string"`
	ReuseUri                      bool    `json:"reuse-uri,omitempty,string"`
	RpcSaveUploadMetadata         string  `json:"rpc-save-upload-metadata,omitempty"`
	SeedRatio                     float32 `json:"seed-ratio,omitempty,string"`
	SeedTime                      uint    `json:"seed-time,omitempty,string"`
	SelectFile                    bool    `json:"select-file,omitempty,string"`
	Split                         uint    `json:"split,omitempty,string"`
	SshHostKeyMd                  string  `json:"ssh-host-key-md,omitempty"`
	StreamPieceSelector           string  `json:"stream-piece-selector,omitempty"`
	Timeout                       uint    `json:"timeout,omitempty,string"`
	UriSelector                   string  `json:"uri-selector,omitempty"`
	UseHead                       bool    `json:"use-head,omitempty,string"`
	UserAgent                     string  `json:"user-agent,omitempty"`
}
